apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
  namespace: hazelcast-ns
  labels:
    app: hazelcast-app
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast'
  version: '5.3.5-slim'
  customConfigCmName: hazelcast-config
  exposeExternally:
    type: Unisocket
    discoveryServiceType: LoadBalancer
