services:
  cassandra-1:
    image: cassandra:latest
    hostname: server1
    restart: on-failure

    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml

    ports:
      - "127.0.0.1:7000:7000"
      - "127.0.0.1:9042:9042"

    environment:
      - MAX_HEAP_SIZE
      - HEAP_NEWSIZE

    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  cassandra-2:
    image: cassandra:latest
    hostname: server2
    restart: on-failure

    ports:
      - "127.0.0.1:9043:9042"

    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml

    environment:
      - MAX_HEAP_SIZE
      - HEAP_NEWSIZE
      - CASSANDRA_SEEDS=server1

    depends_on:
      cassandra-1:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  cassandra-3:
    image: cassandra:latest
    hostname: server3
    restart: on-failure

    ports:
      - "127.0.0.1:9044:9042"

    volumes:
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml

    environment:
      - MAX_HEAP_SIZE
      - HEAP_NEWSIZE
      - CASSANDRA_SEEDS=server1

    depends_on:
      cassandra-2:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "nodetool status"]
      interval: 2m
      start_period: 2m
      timeout: 10s
      retries: 3

  seeder:
    image: cassandra:latest

    depends_on:
      cassandra-1:
        condition: service_healthy

    volumes:
      - ./schema.cql:/schema.cql:ro

    command: /bin/bash -c "cqlsh server1 -f /schema.cql"
