networks:
  neo4j-internal:

services:
  node1:
    image: neo4j:enterprise
    hostname: node1

    networks:
      neo4j-internal:
        aliases:
          - neo4j-network

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./logs/node1:/logs
      - ./conf/node1:/conf

    environment:
      - NEO4J_AUTH
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_EDITION
      - EXTENDED_CONF
      - NEO4J_initial_server_mode__constraint=PRIMARY

    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
    user: ${USER_ID}:${GROUP_ID}

  node2:
    image: neo4j:enterprise
    hostname: node2

    networks:
      neo4j-internal:
        aliases:
          - neo4j-network

    ports:
      - "7475:7474"
      - "7688:7687"

    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./logs/node2:/logs
      - ./conf/node2:/conf

    environment:
      - NEO4J_AUTH
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_EDITION
      - EXTENDED_CONF
      - NEO4J_initial_server_mode__constraint=PRIMARY

    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
    user: ${USER_ID}:${GROUP_ID}

  node3:
    image: neo4j:enterprise
    hostname: node3

    networks:
      neo4j-internal:
        aliases:
          - neo4j-network

    ports:
      - "7476:7474"
      - "7689:7687"

    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./logs/node3:/logs
      - ./conf/node3:/conf

    environment:
      - NEO4J_AUTH
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_EDITION
      - EXTENDED_CONF
      - NEO4J_initial_server_mode__constraint=PRIMARY

    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
    user: ${USER_ID}:${GROUP_ID}

  node4:
    image: neo4j:enterprise
    hostname: node4

    networks:
      neo4j-internal:
        aliases:
          - neo4j-network

    ports:
      - "7477:7474"
      - "7690:7687"

    volumes:
      - ./neo4j.conf:/conf/neo4j.conf
      - ./logs/node4:/logs
      - ./conf/node4:/conf

    environment:
      - NEO4J_AUTH
      - NEO4J_ACCEPT_LICENSE_AGREEMENT
      - NEO4J_EDITION
      - EXTENDED_CONF
      - NEO4J_initial_server_mode__constraint=SECONDARY

    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1" ]
    user: ${USER_ID}:${GROUP_ID}
