services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    hostname: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./user_counter.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
